spring.application.name=store

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE (Neon PostgreSQL)
# ===============================
# Replace YOUR_NEON_URL with your actual Neon database URL
spring.datasource.url=jdbc:postgresql://ep-green-leaf-aimjvu4j-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require&user=neondb_owner&password=npg_7EbcpYaZXU0r
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7EbcpYaZXU0r
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

